// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ChromeBrowser
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AccessingChrome - Use 'AccessingChromeParams' to pass parameters into this method.
        /// </summary>
        public void AccessingChrome()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinEdit uINomeEdit = this.UIMenuIniciarWindow.UIGoogleChromeListItem.UINomeEdit;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(22, 20));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chr'
            Keyboard.SendKeys(this.AccessingChromeParams.SendKeys, ModifierKeys.None);

            // Click 'Nome' text box
            Mouse.Click(uINomeEdit, new Point(61, 8));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.AccessingChromeParams.UIBarradeendereçoedepeEditSendKeys, true);

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(193, 10));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.AccessingChromeParams.UIBarradeendereçoedepeEditSendKeys1, true);
        }
        
        /// <summary>
        /// Verifying if the table shown is correct
        /// </summary>
        public void VerifyingTable()
        {
            #region Variable Declarations
            WinControl uIChromeLegacyWindowDocument = this.UINovaguiaGoogleChromeWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Verify that the 'ControlType' property of 'Chrome Legacy Window' document contains 'Red,Turquoise,Grey,Indigo,3,17,5,6'
            StringAssert.Contains(uIChromeLegacyWindowDocument.ControlType.ToString(), this.VerifyingTableExpectedValues.UIChromeLegacyWindowDocumentControlType, "Page incorrect");
        }
        
        /// <summary>
        /// TestChrome - Use 'TestChromeParams' to pass parameters into this method.
        /// </summary>
        public void TestChrome()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinListItem uIGoogleChromeListItem = this.UIMenuIniciarWindow.UIProgramasGroup.UIGoogleChromeListItem;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(28, 18));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chrome'
            Keyboard.SendKeys(this.TestChromeParams.SendKeys, ModifierKeys.None);

            // Click 'Google Chrome' list item
            Mouse.Click(uIGoogleChromeListItem, new Point(0, 0));

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(210, 18));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.TestChromeParams.UIBarradeendereçoedepeEditSendKeys, true);
        }
        
        /// <summary>
        /// TestingChrome - Use 'TestingChromeParams' to pass parameters into this method.
        /// </summary>
        public void TestingChrome()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(35, 17));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chrome{Enter}'
            Keyboard.SendKeys(this.TestingChromeParams.SendKeys, ModifierKeys.None);

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(267, 19));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.TestingChromeParams.UIBarradeendereçoedepeEditSendKeys, true);
        }
        
        /// <summary>
        /// ChromeTesting - Use 'ChromeTestingParams' to pass parameters into this method.
        /// </summary>
        public void ChromeTesting()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinListItem uIGoogleChromeListItem = this.UIMenuIniciarWindow.UIProgramasGroup.UIGoogleChromeListItem;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(28, 18));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chrome'
            Keyboard.SendKeys(this.ChromeTestingParams.SendKeys, ModifierKeys.None);

            // Click 'Google Chrome' list item
            Mouse.Click(uIGoogleChromeListItem, new Point(0, 0));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys1, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys2, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys3, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys4, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys5, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys6, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys7, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys8, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys9, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys10, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestingParams.UIBarradeendereçoedepeEditSendKeys11, true);
        }
        
        /// <summary>
        /// ChromeTest - Use 'ChromeTestParams' to pass parameters into this method.
        /// </summary>
        public void ChromeTest()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinListItem uIGoogleChromeListItem = this.UIMenuIniciarWindow.UIProgramasGroup.UIGoogleChromeListItem;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(26, 28));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chrome'
            Keyboard.SendKeys(this.ChromeTestParams.SendKeys, ModifierKeys.None);

            // Click 'Google Chrome' list item
            Mouse.Click(uIGoogleChromeListItem, new Point(0, 0));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestParams.UIBarradeendereçoedepeEditSendKeys, true);

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestParams.UIBarradeendereçoedepeEditSendKeys1, true);
        }
        
        /// <summary>
        /// oi - Use 'oiParams' to pass parameters into this method.
        /// </summary>
        public void oi()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinListItem uIGoogleChromeListItem = this.UIMenuIniciarWindow.UIProgramasGroup.UIGoogleChromeListItem;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(34, 17));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chrome'
            Keyboard.SendKeys(this.oiParams.SendKeys, ModifierKeys.None);

            // Click 'Google Chrome' list item
            Mouse.Click(uIGoogleChromeListItem, new Point(0, 0));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.oiParams.UIBarradeendereçoedepeEditSendKeys, true);

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(188, 11));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.oiParams.UIBarradeendereçoedepeEditSendKeys1, true);
        }
        
        /// <summary>
        /// ChromeTest1 - Use 'ChromeTest1Params' to pass parameters into this method.
        /// </summary>
        public void ChromeTest1()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinClient uIChromeLegacyWindowClient = this.UINovaguiaGoogleChromeWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowClient;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(27, 31));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chrome{Enter}'
            Keyboard.SendKeys(this.ChromeTest1Params.SendKeys, ModifierKeys.None);

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(441, 294));

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(253, 8));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTest1Params.UIBarradeendereçoedepeEditSendKeys, true);
        }
        
        /// <summary>
        /// Chrome2 - Use 'Chrome2Params' to pass parameters into this method.
        /// </summary>
        public void Chrome2()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinListItem uIGoogleChromeListItem = this.UIMenuIniciarWindow.UIProgramasGroup.UIGoogleChromeListItem;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(27, 21));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chro'
            Keyboard.SendKeys(this.Chrome2Params.SendKeys, ModifierKeys.None);

            // Click 'Google Chrome' list item
            Mouse.Click(uIGoogleChromeListItem, new Point(0, 0));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.Chrome2Params.UIBarradeendereçoedepeEditSendKeys, true);

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(289, 9));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.Chrome2Params.UIBarradeendereçoedepeEditSendKeys1, true);
        }
        
        /// <summary>
        /// Chrome1 - Use 'Chrome1Params' to pass parameters into this method.
        /// </summary>
        public void Chrome1()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinListItem uIGoogleChromeListItem = this.UIMenuIniciarWindow.UIProgramasGroup.UIGoogleChromeListItem;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(23, 31));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chrome'
            Keyboard.SendKeys(this.Chrome1Params.SendKeys, ModifierKeys.None);

            // Click 'Google Chrome' list item
            Mouse.Click(uIGoogleChromeListItem, new Point(0, 0));

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(172, 13));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.Chrome1Params.UIBarradeendereçoedepeEditSendKeys, true);
        }
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinListItem uIGoogleChromeListItem = this.UIMenuIniciarWindow.UIProgramasGroup.UIGoogleChromeListItem;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            WinClient uIChromeLegacyWindowClient = this.UINovaguiaGoogleChromeWindow.UIChromeLegacyWindowWindow2.UIChromeLegacyWindowClient;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(20, 23));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chrome'
            Keyboard.SendKeys(this.RecordedMethod1Params.SendKeys, ModifierKeys.None);

            // Click 'Google Chrome' list item
            Mouse.Click(uIGoogleChromeListItem, new Point(0, 0));

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(307, 17));

            // Type '********' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.RecordedMethod1Params.UIBarradeendereçoedepeEditSendKeys, true);

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(467, 9));
        }
        
        /// <summary>
        /// Test if the website can be accessed correctly
        /// </summary>
        public void ChromeTestBrowse()
        {
            #region Variable Declarations
            WinButton uIIniciarButton = this.UIIniciarWindow.UIIniciarButton;
            WinEdit uICaixadePesquisaEdit = this.UIMenuIniciarWindow.UIPesquisarprogramaseaPane.UICaixadePesquisaEdit;
            WinListItem uIGoogleChromeListItem = this.UIMenuIniciarWindow.UIProgramasGroup.UIGoogleChromeListItem;
            WinEdit uIBarradeendereçoedepeEdit = this.UINovaguiaGoogleChromeWindow.UIItemGroup.UIBarradeendereçoedepeEdit;
            #endregion

            // Click 'Iniciar' button
            Mouse.Click(uIIniciarButton, new Point(31, 27));

            // Click 'Caixa de Pesquisa' text box
            Mouse.Click(uICaixadePesquisaEdit, new Point(0, 0));

            // Type 'chrome'
            Keyboard.SendKeys(this.ChromeTestBrowseParams.SendKeys, ModifierKeys.None);

            // Click 'Google Chrome' list item
            Mouse.Click(uIGoogleChromeListItem, new Point(0, 0));

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(282, 16));

            // Click 'Barra de endereço e de pesquisa' text box
            Mouse.Click(uIBarradeendereçoedepeEdit, new Point(137, 16));

            // Type '/{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestBrowseParams.UIBarradeendereçoedepeEditSendKeys, ModifierKeys.None);

            // Type 'localhost/PaintWebSite/PaintStore.aspx{Enter}' in 'Barra de endereço e de pesquisa' text box
            Keyboard.SendKeys(uIBarradeendereçoedepeEdit, this.ChromeTestBrowseParams.UIBarradeendereçoedepeEditSendKeys1, ModifierKeys.None);
        }
        
        /// <summary>
        /// Virify if the website can be accessed correctly using IE browser
        /// </summary>
        public void IETestBrowser()
        {
            #region Variable Declarations
            HtmlImage uIREUTERSRubenSprichImage = this.UIMSNCanadaOutlookSkypWindow.UIMSNCanadaOutlookSkypDocument.UIMainCustom.UIREUTERSRubenSprichImage;
            BrowserWindow uIMSNCanadaOutlookSkypWindow = this.UIMSNCanadaOutlookSkypWindow;
            #endregion

            // Go to web page 'http://go.microsoft.com/fwlink/?LinkId=69157' using new browser instance
            this.UIMSNCanadaOutlookSkypWindow.LaunchUrl(new System.Uri(this.IETestBrowserParams.UIMSNCanadaOutlookSkypWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'REUTERS/Ruben Sprich' image at (1, 1)
            Mouse.Hover(uIREUTERSRubenSprichImage, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Go to web page 'http://localhost/PaintWebSite/PaintStore.aspx'
            uIMSNCanadaOutlookSkypWindow.NavigateToUrl(new System.Uri(this.IETestBrowserParams.UIMSNCanadaOutlookSkypWindowUrl1));
        }
        
        /// <summary>
        /// Test - Use 'TestExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Test()
        {
            #region Variable Declarations
            WinControl uIChromeLegacyWindowDocument = this.UINovaguiaGoogleChromeWindow.UIChromeLegacyWindowWindow4.UIChromeLegacyWindowDocument;
            #endregion

            // Verify that the 'Name' property of 'Chrome Legacy Window' document equals 'Red'
            Assert.AreEqual(this.TestExpectedValues.UIChromeLegacyWindowDocumentName, uIChromeLegacyWindowDocument.Name, "Incorrect");
        }
        
        #region Properties
        public virtual AccessingChromeParams AccessingChromeParams
        {
            get
            {
                if ((this.mAccessingChromeParams == null))
                {
                    this.mAccessingChromeParams = new AccessingChromeParams();
                }
                return this.mAccessingChromeParams;
            }
        }
        
        public virtual VerifyingTableExpectedValues VerifyingTableExpectedValues
        {
            get
            {
                if ((this.mVerifyingTableExpectedValues == null))
                {
                    this.mVerifyingTableExpectedValues = new VerifyingTableExpectedValues();
                }
                return this.mVerifyingTableExpectedValues;
            }
        }
        
        public virtual TestChromeParams TestChromeParams
        {
            get
            {
                if ((this.mTestChromeParams == null))
                {
                    this.mTestChromeParams = new TestChromeParams();
                }
                return this.mTestChromeParams;
            }
        }
        
        public virtual TestingChromeParams TestingChromeParams
        {
            get
            {
                if ((this.mTestingChromeParams == null))
                {
                    this.mTestingChromeParams = new TestingChromeParams();
                }
                return this.mTestingChromeParams;
            }
        }
        
        public virtual ChromeTestingParams ChromeTestingParams
        {
            get
            {
                if ((this.mChromeTestingParams == null))
                {
                    this.mChromeTestingParams = new ChromeTestingParams();
                }
                return this.mChromeTestingParams;
            }
        }
        
        public virtual ChromeTestParams ChromeTestParams
        {
            get
            {
                if ((this.mChromeTestParams == null))
                {
                    this.mChromeTestParams = new ChromeTestParams();
                }
                return this.mChromeTestParams;
            }
        }
        
        public virtual oiParams oiParams
        {
            get
            {
                if ((this.moiParams == null))
                {
                    this.moiParams = new oiParams();
                }
                return this.moiParams;
            }
        }
        
        public virtual ChromeTest1Params ChromeTest1Params
        {
            get
            {
                if ((this.mChromeTest1Params == null))
                {
                    this.mChromeTest1Params = new ChromeTest1Params();
                }
                return this.mChromeTest1Params;
            }
        }
        
        public virtual Chrome2Params Chrome2Params
        {
            get
            {
                if ((this.mChrome2Params == null))
                {
                    this.mChrome2Params = new Chrome2Params();
                }
                return this.mChrome2Params;
            }
        }
        
        public virtual Chrome1Params Chrome1Params
        {
            get
            {
                if ((this.mChrome1Params == null))
                {
                    this.mChrome1Params = new Chrome1Params();
                }
                return this.mChrome1Params;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual ChromeTestBrowseParams ChromeTestBrowseParams
        {
            get
            {
                if ((this.mChromeTestBrowseParams == null))
                {
                    this.mChromeTestBrowseParams = new ChromeTestBrowseParams();
                }
                return this.mChromeTestBrowseParams;
            }
        }
        
        public virtual IETestBrowserParams IETestBrowserParams
        {
            get
            {
                if ((this.mIETestBrowserParams == null))
                {
                    this.mIETestBrowserParams = new IETestBrowserParams();
                }
                return this.mIETestBrowserParams;
            }
        }
        
        public virtual TestExpectedValues TestExpectedValues
        {
            get
            {
                if ((this.mTestExpectedValues == null))
                {
                    this.mTestExpectedValues = new TestExpectedValues();
                }
                return this.mTestExpectedValues;
            }
        }
        
        public UIIniciarWindow UIIniciarWindow
        {
            get
            {
                if ((this.mUIIniciarWindow == null))
                {
                    this.mUIIniciarWindow = new UIIniciarWindow();
                }
                return this.mUIIniciarWindow;
            }
        }
        
        public UIMenuIniciarWindow UIMenuIniciarWindow
        {
            get
            {
                if ((this.mUIMenuIniciarWindow == null))
                {
                    this.mUIMenuIniciarWindow = new UIMenuIniciarWindow();
                }
                return this.mUIMenuIniciarWindow;
            }
        }
        
        public UINovaguiaGoogleChromeWindow UINovaguiaGoogleChromeWindow
        {
            get
            {
                if ((this.mUINovaguiaGoogleChromeWindow == null))
                {
                    this.mUINovaguiaGoogleChromeWindow = new UINovaguiaGoogleChromeWindow();
                }
                return this.mUINovaguiaGoogleChromeWindow;
            }
        }
        
        public UIMSNCanadaOutlookSkypWindow UIMSNCanadaOutlookSkypWindow
        {
            get
            {
                if ((this.mUIMSNCanadaOutlookSkypWindow == null))
                {
                    this.mUIMSNCanadaOutlookSkypWindow = new UIMSNCanadaOutlookSkypWindow();
                }
                return this.mUIMSNCanadaOutlookSkypWindow;
            }
        }
        #endregion
        
        #region Fields
        private AccessingChromeParams mAccessingChromeParams;
        
        private VerifyingTableExpectedValues mVerifyingTableExpectedValues;
        
        private TestChromeParams mTestChromeParams;
        
        private TestingChromeParams mTestingChromeParams;
        
        private ChromeTestingParams mChromeTestingParams;
        
        private ChromeTestParams mChromeTestParams;
        
        private oiParams moiParams;
        
        private ChromeTest1Params mChromeTest1Params;
        
        private Chrome2Params mChrome2Params;
        
        private Chrome1Params mChrome1Params;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private ChromeTestBrowseParams mChromeTestBrowseParams;
        
        private IETestBrowserParams mIETestBrowserParams;
        
        private TestExpectedValues mTestExpectedValues;
        
        private UIIniciarWindow mUIIniciarWindow;
        
        private UIMenuIniciarWindow mUIMenuIniciarWindow;
        
        private UINovaguiaGoogleChromeWindow mUINovaguiaGoogleChromeWindow;
        
        private UIMSNCanadaOutlookSkypWindow mUIMSNCanadaOutlookSkypWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AccessingChrome'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class AccessingChromeParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'chr'
        /// </summary>
        public string SendKeys = "chr";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "WpYLUN/3BV5V+Z9lEB/Smh4TBvdQhvdn";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys1 = "2OQv9u36yqy+Iy9bx42AzBwQV6MMPDrs0BXRxS6ht6hkzeBxkJP4RF7OpKIQ5JcHirdVnNS2j7Cb8AHFn" +
            "VFIEk9c4CTozuiR";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'VerifyingTable'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class VerifyingTableExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'Chrome Legacy Window' document contains 'Red,Turquoise,Grey,Indigo,3,17,5,6'
        /// </summary>
        public string UIChromeLegacyWindowDocumentControlType = "Red,Turquoise,Grey,Indigo,3,17,5,6";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestChrome'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class TestChromeParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'chrome'
        /// </summary>
        public string SendKeys = "chrome";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "WpYLUN/3BV4ki90U7iQ8wBjaOL88mrfjntgmT2G+WCK3l32Pm7/Gyt+Birug4U+zwfXWm8PLzsWaJ9MVV" +
            "PIhO8z5ldx3hpya";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestingChrome'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class TestingChromeParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'chrome{Enter}'
        /// </summary>
        public string SendKeys = "chrome{Enter}";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "WpYLUN/3BV4ki90U7iQ8wBjaOL88mrfjWMFhoW2VRThYoCvgrbm6KUfs4EXH6njTnWbG60Un5v2AMB6wg" +
            "U5gPQ==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ChromeTesting'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class ChromeTestingParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'chrome'
        /// </summary>
        public string SendKeys = "chrome";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "WpYLUN/3BV6+s8Lie+Szo5UboW1B1UGm7v5OJTR2CXeAn11QW81mP7Rn/9vVwbHY";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys1 = "YN/mQM5J9PQyaTrMeVvgM6oda6PHLJpACh3Ic0UOK9OAJ7VA8ED5zg==";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys2 = "+UTsLjaeaR+ao6HAcDK8bI2M08ozCs37V1VamOLvFxLiJqMfrmMsDrKzDQmo3CB2";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys3 = "+UTsLjaeaR9wenQhjQzT+MDHR9sdEmLdyHzUBND6x8SCYBqaO8zCngEvBNSyAn0cMKYqMYdd/i/DZuiqU" +
            "dJ5Ed5eS2aNwY2l";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys4 = "+UTsLjaeaR+ao6HAcDK8bI2M08ozCs37V1VamOLvFxLiJqMfrmMsDrKzDQmo3CB2";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys5 = "+UTsLjaeaR+neDbN+m2hSoOjCNuEo2hBzPP7RQ5CeboUzK4OcaAvQy6JUZPkHOCuff0c2vzeld9Bb0uuc" +
            "kKLJHI4swljisDzh1m6a7QPwK0Z2PeDJdEbGA==";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys6 = "+UTsLjaeaR+ao6HAcDK8bI2M08ozCs37V1VamOLvFxLiJqMfrmMsDrKzDQmo3CB2";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys7 = "+UTsLjaeaR8nyE1a1MAezTGG6xUFZluna/FALhUPkA0b0nEcplw3lnX8PsKkvFm4KAFYLuud2DFt4cu16" +
            "gfPG9Ep/arp0bnY";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys8 = "+UTsLjaeaR+ao6HAcDK8bI2M08ozCs37V1VamOLvFxLiJqMfrmMsDrKzDQmo3CB2";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys9 = "+UTsLjaeaR9wenQhjQzT+MDHR9sdEmLdyHzUBND6x8SCYBqaO8zCnuMyCNIA9GQ7itYMoHsae28pCCEwb" +
            "XW0FFEfJM8W7VUl";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys10 = "+UTsLjaeaR+ao6HAcDK8bI2M08ozCs37V1VamOLvFxLiJqMfrmMsDrKzDQmo3CB2";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys11 = "+UTsLjaeaR+uGYGykDiAcBBFIgcp8T4BS8JkTXma7V7i1qJYdKK/0A==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ChromeTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class ChromeTestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'chrome'
        /// </summary>
        public string SendKeys = "chrome";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "XYwdFHpTY/HP2Q9oLdmbhbPsmrv2+OoLtJGqIOrluyQ=";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys1 = "GhPfJsLLnFnzeOtqPoDn/esgSJOsPncG0jBCedvtgAmldAAhmcaqijAdHu1hD8YG";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'oi'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class oiParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'chrome'
        /// </summary>
        public string SendKeys = "chrome";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "+EmFc8Y6mtf9o5DpRp5anWZJjAyblqDQ";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys1 = "VwZdtHLD+r4t1Fzxe7GOJtOHf+CuJ7U4XxLEkkLpz8w=";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ChromeTest1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class ChromeTest1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'chrome{Enter}'
        /// </summary>
        public string SendKeys = "chrome{Enter}";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "WpYLUN/3BV5MxhQJv2g8lNrBNiMcy2xRSVFf2NyJ6XnVrjV0zhQnAEN+z+c3OhUhFl3cLJldiDj/pVluI" +
            "Wnu/QspKXnaTrIIQXiSD7hlKdD8CxDTwYAUnw==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Chrome2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class Chrome2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'chro'
        /// </summary>
        public string SendKeys = "chro";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "j1EU9mpnI2EHbvyXBgTEJJPAdnEEOPY3qWIGXtWBE1qIKtRhCsB1QxDXwlQX6kqtX8ZervO90deOlRQtE" +
            "/EYCw==";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys1 = "+k74xQ3nEIIb/WmLWf6YTlg7e9yRf2FLbYwAjREeM6SIGD9Pj4yAN4p1hcp7T0GP1v+G4oQPjapup7+Hs" +
            "woUarFBjPsoTEmNjQOL0ypeT48gnGbQBlDJzMXW+wN6eT7Jd2exAvAu+yMjabPIJ2/5Pw==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Chrome1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class Chrome1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'chrome'
        /// </summary>
        public string SendKeys = "chrome";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "WpYLUN/3BV4ki90U7iQ8wBjaOL88mrfjdtJocQ5csa6GBT7rKMoE8/cJWBveW/Lf4MGnAz3nWUI7SQk4q" +
            "oDeetzcYd6TEt8rXKsSqqVObyUJCqtmlcllUQ==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'chrome'
        /// </summary>
        public string SendKeys = "chrome";
        
        /// <summary>
        /// Type '********' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "aG6K21cmPKnU5HIso4tfig==";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ChromeTestBrowse'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class ChromeTestBrowseParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'chrome'
        /// </summary>
        public string SendKeys = "chrome";
        
        /// <summary>
        /// Type '/{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys = "/{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}";
        
        /// <summary>
        /// Type 'localhost/PaintWebSite/PaintStore.aspx{Enter}' in 'Barra de endereço e de pesquisa' text box
        /// </summary>
        public string UIBarradeendereçoedepeEditSendKeys1 = "localhost/PaintWebSite/PaintStore.aspx{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'IETestBrowser'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class IETestBrowserParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/?LinkId=69157' using new browser instance
        /// </summary>
        public string UIMSNCanadaOutlookSkypWindowUrl = "http://go.microsoft.com/fwlink/?LinkId=69157";
        
        /// <summary>
        /// Go to web page 'http://localhost/PaintWebSite/PaintStore.aspx'
        /// </summary>
        public string UIMSNCanadaOutlookSkypWindowUrl1 = "http://localhost/PaintWebSite/PaintStore.aspx";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Test'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class TestExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Name' property of 'Chrome Legacy Window' document equals 'Red'
        /// </summary>
        public string UIChromeLegacyWindowDocumentName = "Red";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIIniciarWindow : WinWindow
    {
        
        public UIIniciarWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Iniciar";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("Iniciar");
            #endregion
        }
        
        #region Properties
        public WinButton UIIniciarButton
        {
            get
            {
                if ((this.mUIIniciarButton == null))
                {
                    this.mUIIniciarButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIIniciarButton.SearchProperties[WinButton.PropertyNames.Name] = "Iniciar";
                    this.mUIIniciarButton.WindowTitles.Add("Iniciar");
                    #endregion
                }
                return this.mUIIniciarButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIIniciarButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMenuIniciarWindow : WinWindow
    {
        
        public UIMenuIniciarWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Menu Iniciar";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DV2ControlHost";
            this.WindowTitles.Add("Menu Iniciar");
            #endregion
        }
        
        #region Properties
        public UIPesquisarprogramaseaPane UIPesquisarprogramaseaPane
        {
            get
            {
                if ((this.mUIPesquisarprogramaseaPane == null))
                {
                    this.mUIPesquisarprogramaseaPane = new UIPesquisarprogramaseaPane(this);
                }
                return this.mUIPesquisarprogramaseaPane;
            }
        }
        
        public UIGoogleChromeListItem UIGoogleChromeListItem
        {
            get
            {
                if ((this.mUIGoogleChromeListItem == null))
                {
                    this.mUIGoogleChromeListItem = new UIGoogleChromeListItem(this);
                }
                return this.mUIGoogleChromeListItem;
            }
        }
        
        public UIProgramasGroup UIProgramasGroup
        {
            get
            {
                if ((this.mUIProgramasGroup == null))
                {
                    this.mUIProgramasGroup = new UIProgramasGroup(this);
                }
                return this.mUIProgramasGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIPesquisarprogramaseaPane mUIPesquisarprogramaseaPane;
        
        private UIGoogleChromeListItem mUIGoogleChromeListItem;
        
        private UIProgramasGroup mUIProgramasGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIPesquisarprogramaseaPane : WinPane
    {
        
        public UIPesquisarprogramaseaPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Pesquisar programas e arquivos";
            this.WindowTitles.Add("Menu Iniciar");
            #endregion
        }
        
        #region Properties
        public WinEdit UICaixadePesquisaEdit
        {
            get
            {
                if ((this.mUICaixadePesquisaEdit == null))
                {
                    this.mUICaixadePesquisaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICaixadePesquisaEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Caixa de Pesquisa";
                    this.mUICaixadePesquisaEdit.WindowTitles.Add("Menu Iniciar");
                    #endregion
                }
                return this.mUICaixadePesquisaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICaixadePesquisaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIGoogleChromeListItem : WinListItem
    {
        
        public UIGoogleChromeListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Google Chrome";
            this.WindowTitles.Add("Menu Iniciar");
            #endregion
        }
        
        #region Properties
        public WinEdit UINomeEdit
        {
            get
            {
                if ((this.mUINomeEdit == null))
                {
                    this.mUINomeEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINomeEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Nome";
                    this.mUINomeEdit.WindowTitles.Add("Menu Iniciar");
                    #endregion
                }
                return this.mUINomeEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINomeEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIProgramasGroup : WinGroup
    {
        
        public UIProgramasGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Programas";
            this.WindowTitles.Add("Menu Iniciar");
            #endregion
        }
        
        #region Properties
        public WinListItem UIGoogleChromeListItem
        {
            get
            {
                if ((this.mUIGoogleChromeListItem == null))
                {
                    this.mUIGoogleChromeListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIGoogleChromeListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Google Chrome";
                    this.mUIGoogleChromeListItem.WindowTitles.Add("Menu Iniciar");
                    #endregion
                }
                return this.mUIGoogleChromeListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIGoogleChromeListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UINovaguiaGoogleChromeWindow : WinWindow
    {
        
        public UINovaguiaGoogleChromeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Nova guia - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Nova guia - Google Chrome");
            this.WindowTitles.Add("PaintStore - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow1
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow1 == null))
                {
                    this.mUIChromeLegacyWindowWindow1 = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow2 UIChromeLegacyWindowWindow2
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow2 == null))
                {
                    this.mUIChromeLegacyWindowWindow2 = new UIChromeLegacyWindowWindow2(this);
                }
                return this.mUIChromeLegacyWindowWindow2;
            }
        }
        
        public UIChromeLegacyWindowWindow3 UIChromeLegacyWindowWindow3
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow3 == null))
                {
                    this.mUIChromeLegacyWindowWindow3 = new UIChromeLegacyWindowWindow3(this);
                }
                return this.mUIChromeLegacyWindowWindow3;
            }
        }
        
        public UIChromeLegacyWindowWindow4 UIChromeLegacyWindowWindow4
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow4 == null))
                {
                    this.mUIChromeLegacyWindowWindow4 = new UIChromeLegacyWindowWindow4(this);
                }
                return this.mUIChromeLegacyWindowWindow4;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow1;
        
        private UIChromeLegacyWindowWindow2 mUIChromeLegacyWindowWindow2;
        
        private UIChromeLegacyWindowWindow3 mUIChromeLegacyWindowWindow3;
        
        private UIChromeLegacyWindowWindow4 mUIChromeLegacyWindowWindow4;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Nova guia - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIBarradeendereçoedepeEdit
        {
            get
            {
                if ((this.mUIBarradeendereçoedepeEdit == null))
                {
                    this.mUIBarradeendereçoedepeEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIBarradeendereçoedepeEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Barra de endereço e de pesquisa";
                    this.mUIBarradeendereçoedepeEdit.WindowTitles.Add("Nova guia - Google Chrome");
                    #endregion
                }
                return this.mUIBarradeendereçoedepeEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIBarradeendereçoedepeEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "131269632";
            this.WindowTitles.Add("PaintStore - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("PaintStore - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "113965824";
            this.WindowTitles.Add("Nova guia - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Nova guia - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow2 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "202985536";
            this.WindowTitles.Add("Nova guia - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Nova guia - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow3 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "140125248";
            this.WindowTitles.Add("PaintStore - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("PaintStore - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIChromeLegacyWindowWindow4 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "200275840";
            this.WindowTitles.Add("PaintStore - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("PaintStore - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMSNCanadaOutlookSkypWindow : BrowserWindow
    {
        
        public UIMSNCanadaOutlookSkypWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN Canada - Outlook, Skype, Bing and Latest News";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN Canada - Outlook, Skype, Bing and Latest News");
            this.WindowTitles.Add("PaintStore");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIMSNCanadaOutlookSkypDocument UIMSNCanadaOutlookSkypDocument
        {
            get
            {
                if ((this.mUIMSNCanadaOutlookSkypDocument == null))
                {
                    this.mUIMSNCanadaOutlookSkypDocument = new UIMSNCanadaOutlookSkypDocument(this);
                }
                return this.mUIMSNCanadaOutlookSkypDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMSNCanadaOutlookSkypDocument mUIMSNCanadaOutlookSkypDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMSNCanadaOutlookSkypDocument : HtmlDocument
    {
        
        public UIMSNCanadaOutlookSkypDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MSN Canada - Outlook, Skype, Bing and Latest News";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/en-ca/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.msn.com/en-ca/?ocid=iehp";
            this.WindowTitles.Add("MSN Canada - Outlook, Skype, Bing and Latest News");
            #endregion
        }
        
        #region Properties
        public UIMainCustom UIMainCustom
        {
            get
            {
                if ((this.mUIMainCustom == null))
                {
                    this.mUIMainCustom = new UIMainCustom(this);
                }
                return this.mUIMainCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIMainCustom mUIMainCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMainCustom : HtmlCustom
    {
        
        public UIMainCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "main";
            this.SearchProperties["Id"] = "main";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"main\" role=\"main\" data-m=\"{\'i\':34,\'n";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("MSN Canada - Outlook, Skype, Bing and Latest News");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIREUTERSRubenSprichImage
        {
            get
            {
                if ((this.mUIREUTERSRubenSprichImage == null))
                {
                    this.mUIREUTERSRubenSprichImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIREUTERSRubenSprichImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIREUTERSRubenSprichImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIREUTERSRubenSprichImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIREUTERSRubenSprichImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/tenant/amp/entityid/AA8uLJX.img";
                    this.mUIREUTERSRubenSprichImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://img.s-msn.com/tenant/amp/entityid/AA8uLJX.img?h=368&w=622&m=6&q=60&u=t&o=t" +
                        "&l=f&f=jpg&x=1691&y=573";
                    this.mUIREUTERSRubenSprichImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/en-ca/money/topstories/inside-davos/ss-AA8vLHo";
                    this.mUIREUTERSRubenSprichImage.FilterProperties[HtmlImage.PropertyNames.Href] = "http://www.msn.com/en-ca/money/topstories/inside-davos/ss-AA8vLHo";
                    this.mUIREUTERSRubenSprichImage.FilterProperties[HtmlImage.PropertyNames.Class] = "image defer loaded";
                    this.mUIREUTERSRubenSprichImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "width=\"618\" title=\"REUTERS/Ruben Sprich\"";
                    this.mUIREUTERSRubenSprichImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "19";
                    this.mUIREUTERSRubenSprichImage.WindowTitles.Add("MSN Canada - Outlook, Skype, Bing and Latest News");
                    #endregion
                }
                return this.mUIREUTERSRubenSprichImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIREUTERSRubenSprichImage;
        #endregion
    }
}
